
always_for_in = true
disallow_single_arg_nesting = true
join_lines_based_on_source = false
normalize_line_endings = "unix"
remove_extra_newlines = true
short_to_long_function_def = true
trailing_comma = false
whitespace_ops_in_indices = true
whitespace_typedefs = true
yas_style_nesting = false
import_to_using = false