repos:
  - repo: local
    hooks:
      - id: julia-format
        name: Julia Formatter
        entry: julia --project=. -e 'using JuliaFormatter; format(".")'
        language: system
        types: [julia]
        pass_filenames: false 