[architecture.dense_neural_network]
in_features = [1, 1]
out_features = 1
hidden_features = [16, 16, 16, 16]
dropout = 0.001

[training]
batch_size = 256
num_epochs = 200

[optimizer]
type = "adamw"
learning_rate = 0.0001
weight_decay = 0.0001

[model.stochastic_interpolant]
interpolant_type = "linear"