[architecture.dense_neural_network]
in_features = [1, 1]
out_features = 1
hidden_features = [32, 32, 32]
dropout = 0.1

[training]
batch_size = 256
num_epochs = 1000

[optimizer]
type = "adamw"
learning_rate = 0.0001
weight_decay = 0.0001

[model.stochastic_interpolant]
interpolant_type = "linear"